# Generated by Django 3.0.7 on 2020-06-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(default='Null', max_length=100),
        ),
    ]
